---
all:
  children:
    appservers:
      hosts:
        52.36.216.107:
           package_apache: 
             - httpd
           package_lamp:
             - php
             - php-mysqlnd
        35.93.28.15:
           package_apache: 
             - apache2
           package_lamp:
             - php
             - libapache2-mod-php
             - php-mysql
          

    