---
- name: installation of apache and php lamp stack on ubuntu
  hosts: ubuntu
  become: yes
  tasks: 
    - name: installations
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: php 
      ansible.builtin.apt:
        name: 
           - php
           - libapache2-mod-php
           - php-mysql
        state: present
        update_cache: yes
    - name: copy file
      ansible.builtin.copy:
        src: ./kasi.txt
        dest: /var/www/html/info.php